version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: ai-ingres-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart: unless-stopped

  chromadb:
    image: chromadb/chroma:latest
    container_name: ai-ingres-chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma
    restart: unless-stopped

volumes:
  chroma_data:
